version: '3.9'

services:
  server:
    build:
      context: .
    ports:
      # local_port:container_port
      - '8080:8080'
    environment:
      IFTTT_SERVICE_KEY: ''
      MONGO_URI: ''
